{    "name": "Product Auto Code",
    "version": "17.0.2.0.0",
    "summary": "Códigos automáticos para productos y variantes",
    "author": "PrimateUy + Diego + ChatGPT",
    "license": "LGPL-3",
    "website": "https://primate.com.uy",
    "depends": ["product", "stock"],
    "data": ["security/ir.model.access.csv", "data/product_auto_code_actions.xml", "views/product_auto_code_views.xml", "views/res_config_settings_inventory_views.xml"],
    "installable": true,
    "application": false,
}
